profiler/accounts/urls.py
''' accounts specific urls
    urls for the accounts application '''

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^sign_in/$', views.sign_in, name='sign_in'),
    url(r'sign_up/$', views.sign_up, name='sign_up'),
    url(r'sign_out/$', views.sign_out, name='sign_out'),
    url(r'view_profile/$', views.view_profile, name='view_profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'edit_profile/$', views.edit_profile, name='edit_profile'),
]

profiler/profiler/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', views.home, name='home'),
]
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiler/accounts/models.py
''' database models for the accounts application '''

import datetime

from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    ''' user profile model, which extends the User model from Django '''
    user = models.OneToOneField(User)
    date_of_birth = models.DateField(
                    default=datetime.datetime.now().strftime(
                     '%d/%m/%Y'), blank=True, null=True)

    bio = models.CharField(max_length=300, blank=True)
    avatar = models.ImageField(
        upload_to='avatar_imgs/', blank=True)

    def __str__(self):
        return self.user.username

profiler/accounts/forms.py
''' cutsom forms for the accounts application '''

from django import forms
from django.contrib.auth.forms import (UserCreationForm,
                                       PasswordChangeForm)
from django.contrib.auth.models import User

from accounts.models import UserProfile


class SignUpForm(UserCreationForm):
    ''' extends the built-in user creation form, so as to add in
     our extra data '''
    
    date_of_birth = forms.DateTimeField(label='Date of Birth',
                                        input_formats=['%Y-%m-%d',
                                                       '%m/%d/%Y',
                                                       '%d/%m/%y'],
                                        )
    bio = forms.CharField(max_length=300, min_length=10)
    avatar = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            'date_of_birth',
            'bio',
        )

    def save(self, commit=True):
        if not commit:
            raise NotImplementedError("""Can't create User and UserProfile /
                                      without database save""")
        user = super(SignUpForm, self).save(commit=True)
        user_profile = UserProfile(
            user=user,
            date_of_birth=self.cleaned_data['date_of_birth'],
            bio=self.cleaned_data['bio'],
            avatar=self.cleaned_data['avatar'])

        user_profile.save()
        return user, user_profile


class EditProfileForm(forms.ModelForm):
    ''' form to allow changes to the UserProfile '''
    bio = forms.CharField(max_length=300, 
                          min_length=10,
                          help_text='Use at least 10 characters.')

    class Meta:
        model = UserProfile
        fields = (
            'bio',
            'avatar',
        )


class UserUpdateForm(forms.ModelForm):
    """Form for updating user basic information."""

    class Meta:
        model = User
        fields = ('username',
                  'first_name',
                  'last_name',
                  'email',
                  )

profiler/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render


from accounts.forms import (SignUpForm,
                            EditProfileForm,
                            UserUpdateForm)
from accounts.models import UserProfile


def sign_in(request):
    ''' sign in view for the accounts app '''
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(
                        reverse('accounts:view_profile')
                    )
                else:
                    messages.error(
                        request,
                        "That user account has been disabled."
                    )
            else:
                messages.error(
                    request,
                    "Username or password is incorrect."
                )
        else:
            print(form.error_messages)
    return render(request, 'accounts/sign_in.html', {'form': form})


def sign_up(request):
    ''' sign_up view for our accounts application '''
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, user)
            messages.success(
                request,
                "You're now a user! You've been signed in, too."
            )
            return HttpResponseRedirect(reverse('accounts:view_profile'))
        else:
            print(form.error_messages)
    return render(request, 'accounts/sign_up.html', {'form': form})


@login_required
def sign_out(request):
    ''' sign out view for the accounts application '''
    logout(request)
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse('home'))


@login_required
def view_profile(request):
    ''' user profile view for the accounts application '''
    profile = get_object_or_404(UserProfile, user=request.user)
    context = {'user': request.user,
               'avatar': request.FILES,
               'profile': profile
               }
    return render(request, 'accounts/view_profile.html', context)


@login_required
def edit_profile(request):
    ''' edit profile view for the accounts application '''
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = EditProfileForm(request.POST,
                                       request.FILES,
                                       instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse('accounts:view_profile'))
        else:
            print('error occured on form')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = EditProfileForm(instance=request.user.userprofile)
        return render(request, 'accounts/edit_profile.html',
                      {'user_form': user_form, 'profile_form': profile_form})                     


@login_required
def change_password(request):
    ''' a view to allow users to change their password '''
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request,
                             'Your password was successfully updated!'
                             )
            return HttpResponseRedirect(reverse('accounts:view_profile'))
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })

profiler/profiler/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

profiler/accounts/templates/accounts/change_password.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}Change Password | {{user.first_name|capfirst }} {{user.last_name|capfirst}}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:change_password' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Submit Changes">
</form>
{% endblock %}

profiler/accounts/templates/accounts/edit_profile.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}Edit Profile | {{user.first_name|capfirst }} {{user.last_name|capfirst}}{% endblock %}

{% block body %}
<form enctype="multipart/form-data" method="POST" action="{% url 'accounts:edit_profile' %}">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" class="button-primary" value="Submit Changes">
</form>
{% endblock %}

profiler/accounts/templates/accounts/sign_in.html
{% extends "layout.html" %}

{% block title %}Sign In | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_in' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign In">
</form>
{% endblock %}

profiler/accounts/templates/accounts/sign_up.html
{% extends "layout.html" %}

{% block title %}Sign Up | {{ super }}{% endblock %}

{% block body %}
<form enctype="multipart/form-data" method="POST" action="{% url 'accounts:sign_up' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign Up">
</form>
{% endblock %}

profiler/accounts/templates/accounts/view_profile.html
{% extends "layout.html" %}

{% block title %}User Profile | {{user.first_name|capfirst }} {{user.last_name|capfirst}}{% endblock %}

{% block body %}

<h1>{{user.first_name|capfirst }} {{user.last_name|capfirst}}</h1>

<div class="container">
   
    <h1>Profile</h1>
    <p>ID: {{ user.userprofile.user_id }}</p>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Date of Birth: {{ user.userprofile.date_of_birth }}</p>
    <p>Bio: {{ user.userprofile.bio }}</p>

    {% if user.userprofile.avatar %}
    <img src="{{ user.userprofile.avatar.url }}" width="240">
    {% endif %}
    <br>

    <a href="{% url 'accounts:edit_profile'%}" class="button">Edit</a>
        
</div>

{% endblock %}

profiler/templates/home.html
{% extends 'layout.html' %}
{% block body %}
    <div class="grid-25">
        
    </div>
    <div class="grid-75">
        <h1>Welcome!</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad amet assumenda beatae blanditiis, deserunt doloremque ea earum excepturi id, impedit ipsam magnam nulla obcaecati, quidem quis soluta tenetur vitae?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad amet assumenda beatae blanditiis, deserunt doloremque ea earum excepturi id, impedit ipsam magnam nulla obcaecati, quidem quis soluta tenetur vitae?</p>
    </div>
{% endblock %}

profiler/templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Circle{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine'
          rel='stylesheet' type='text/css'>

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/global.css" %}">

    <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript"
            src="{% static "js/autogrow.js" %}"></script>
    <script type="text/javascript" src="{% static "js/global.js" %}"></script>


</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo"><a class="logo"
                                                      href="{% url 'home' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <nav>
                    <ul class="circle--inline">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                        {% endif %}
                     </ul>
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                            <li><a href="{% url 'accounts:sign_in' %}">Sign In</a></li>
                         {% else %}
                            <li><a href="{% url 'accounts:view_profile' %}">View Profile</a></li>
                            <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>>
                            <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

<div class="bounds circle--page">
    {% if messages %}
        <ul class="messages centered grid-50">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% block body %}{% endblock %}
</div>
</body>
</html>